/**
 * Execute a plan that was previously generated by /api/plan.
 *
 * POST { tasks: [{ gameSlug, capability }] }
 *
 * Each task is run via the unified runTask helper, sequentially with a small
 * delay between them to avoid upstream rate limiting. Returns aggregated
 * results.
 */

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { hasAdapter } from "@/adapters";
import { runTask } from "@/lib/tasks/runner";
import { CAPABILITIES, type Plan } from "@/lib/planner/schema";
import type { Capability } from "@/adapters/types";

const CAPABILITY_SET = new Set<string>(CAPABILITIES);
const SPACING_MS = 1500;
const MAX_TASKS = 30;

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: { tasks?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  if (!Array.isArray(body.tasks)) {
    return NextResponse.json(
      { error: "`tasks` must be an array" },
      { status: 400 }
    );
  }
  if (body.tasks.length === 0) {
    return NextResponse.json({ results: [] });
  }
  if (body.tasks.length > MAX_TASKS) {
    return NextResponse.json(
      { error: `Too many tasks (max ${MAX_TASKS} per execute)` },
      { status: 400 }
    );
  }

  const tasks: Plan["tasks"] = [];
  for (const t of body.tasks) {
    if (!t || typeof t !== "object") {
      return NextResponse.json({ error: "Each task must be an object" }, { status: 400 });
    }
    const obj = t as Record<string, unknown>;
    const gameSlug = typeof obj.gameSlug === "string" ? obj.gameSlug : "";
    const capability = typeof obj.capability === "string" ? obj.capability : "";
    const rationale = typeof obj.rationale === "string" ? obj.rationale : "";

    if (!hasAdapter(gameSlug)) {
      return NextResponse.json(
        { error: `Unknown gameSlug: ${gameSlug}` },
        { status: 400 }
      );
    }
    if (!CAPABILITY_SET.has(capability)) {
      return NextResponse.json(
        { error: `Unknown capability: ${capability}` },
        { status: 400 }
      );
    }
    tasks.push({
      gameSlug,
      capability: capability as (typeof CAPABILITIES)[number],
      rationale,
    });
  }

  const results: Array<{
    gameSlug: string;
    capability: string;
    taskId?: string;
    status: string;
    message: string;
    reward?: string;
  }> = [];

  for (let i = 0; i < tasks.length; i++) {
    const t = tasks[i];
    try {
      const { taskId, result } = await runTask({
        userId: session.user.id,
        gameSlug: t.gameSlug,
        capability: t.capability as Capability,
        triggeredBy: "agent",
      });
      results.push({
        gameSlug: t.gameSlug,
        capability: t.capability,
        taskId,
        status: result.status,
        message: result.message,
        reward: result.reward,
      });
    } catch (e) {
      results.push({
        gameSlug: t.gameSlug,
        capability: t.capability,
        status: "failed",
        message: e instanceof Error ? e.message : "Unknown error",
      });
    }
    if (i < tasks.length - 1) {
      await new Promise((r) => setTimeout(r, SPACING_MS));
    }
  }

  return NextResponse.json({ results });
}
